### ISSUE TITLE
binary stl files starting with "solid" in its header

### ISSUE THREAD

**Issue by ag88** [cyanobacterium/STL-Parser-for-Java#1]
some binary stl files starts with "solid" in its header that confuses a parser which depends on "solid" to tell if it is ascii or binary

made some fixes here, you may like to take a look
https://github.com/ag88/stl-viewer/blob/master/src/hall/collin/christopher/stl4j/STLParser.java

**Comment by DrPlantabyte** [comment]
I accepted the pull request. If we're going to do more development on this library, then the project needs a couple of example STL files for testing purposes.

**Comment by ag88** [comment]
no worries about my program, i used your code as i find it among the more 'tidy' implementations and in fact it is one of the implementations that works pretty well. while developing my STL viewer (which uses this STL parser) i downloaded various STL files/models from http://www.thingiverse.com/ and tried them out. you may like to check out my stl viewer program as it is after all based on your parser, you could download the various models from http://www.thingiverse.com and try them out :)
